name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Updated to v3 which supports newer Node.js versions
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x' # Specify the Node.js version
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
